package cc.bitky.jetbrains.plugin.universalgenerate.constants;

/**
 * @author bitkylin
 */
public enum ActionEnum {

    MERGE_SWAGGER_TO_JAVA_DOC_FOR_ELEMENT,
    MERGE_SWAGGER_TO_JAVA_DOC_FOR_FILE,
    PADDING_GENERATE_FOR_ELEMENT,
    PADDING_GENERATE_FOR_FILE,
    PADDING_SWAGGER_TO_JAVA_DOC_FOR_ELEMENT,
    PADDING_SWAGGER_TO_JAVA_DOC_FOR_FILE,
    RENEW_GENERATE_FOR_ELEMENT,
    RENEW_GENERATE_FOR_FILE,
    ;
}
