package cc.bitky.jetbrains.plugin.universalgenerate.constants;

/**
 * @author bitkylin
 */
public enum ActionEnum {

    RE_GENERATE_SWAGGER_TO_JAVA_DOC_FOR_ELEMENT,
    RE_GENERATE_SWAGGER_TO_JAVA_DOC_FOR_FILE,
    RE_GENERATE_ELEMENT_NAME_TO_JAVA_DOC_FOR_ELEMENT,
    RE_GENERATE_ELEMENT_NAME_TO_JAVA_DOC_FOR_FILE,
    POPULATE_MISSING_ANNOTATION_FOR_ELEMENT,
    POPULATE_MISSING_ANNOTATION_FOR_FILE,
    POPULATE_SWAGGER_TO_JAVA_DOC_FOR_ELEMENT,
    POPULATE_SWAGGER_TO_JAVA_DOC_FOR_FILE,
    POPULATE_ELEMENT_NAME_TO_JAVA_DOC_FOR_ELEMENT,
    POPULATE_ELEMENT_NAME_TO_JAVA_DOC_FOR_FILE,
    RE_GENERATE_ANNOTATION_FOR_ELEMENT,
    RE_GENERATE_ANNOTATION_FOR_FILE,
    ;
}
